"""added hash_password , verify_password and set_password in UserModel

Revision ID: 48241765f4e2
Revises: c231207d7ec8
Create Date: 2026-04-30 14:07:54.231176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48241765f4e2'
down_revision: Union[str, Sequence[str], None] = 'c231207d7ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
